# Generated by Django 5.1 on 2024-08-26 16:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskManagement', '0002_remove_task_priority_alter_task_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 26, 16, 45, 44, 33474, tzinfo=datetime.timezone.utc)),
        ),
    ]
