# Generated by Django 5.1 on 2024-08-26 16:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskManagement', '0004_task_priority_alter_task_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('School', 'School'), ('Personal', 'Personal'), ('Work', 'Work'), ('None', 'None')], default='None', max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 26, 16, 50, 15, 555921, tzinfo=datetime.timezone.utc)),
        ),
    ]
