# Generated by Django 5.1 on 2024-08-27 02:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskManagement', '0006_alter_task_due_date_alter_task_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 27, 2, 30, 40, 17994, tzinfo=datetime.timezone.utc)),
        ),
    ]
