# Generated by Django 5.1 on 2024-08-27 16:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskManagement', '0008_alter_task_due_date_assignment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 27, 16, 20, 14, 842648, tzinfo=datetime.timezone.utc)),
        ),
    ]
