# Generated by Django 5.1 on 2024-08-27 18:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskManagement', '0013_alter_task_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='firstName',
            field=models.CharField(choices=[('admin', 'admin'), ('manager', 'Manager'), ('user', 'User')], default='user', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='lastName',
            field=models.CharField(choices=[('admin', 'admin'), ('manager', 'Manager'), ('user', 'User')], default='user', max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 27, 18, 14, 4, 350743, tzinfo=datetime.timezone.utc)),
        ),
    ]
