# Generated by Django 5.1 on 2024-09-06 00:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskManagement', '0026_alter_task_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('completed', 'completed'), ('In Progress', 'In Progress'), ('Incomplete', 'Incomplete')], default='Incomplete', max_length=24),
        ),
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('School', 'School'), ('Personal', 'Personal'), ('Work', 'Work'), ('None', 'None')], default='None', max_length=24),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 6, 0, 33, 13, 169947, tzinfo=datetime.timezone.utc)),
        ),
    ]
