# Generated by Django 3.2.25 on 2024-10-25 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskManagement', '0030_rename_task_id_assignment_task_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
