# Generated by Django 5.1 on 2024-08-26 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_ID', models.BigIntegerField(primary_key=True, serialize=False)),
                ('description', models.TextField(max_length=250)),
                ('due_date', models.DateTimeField(default='01-01-0001')),
                ('priority', models.SmallIntegerField()),
                ('title', models.TextField(max_length=250)),
            ],
        ),
    ]
