# Generated by Django 5.1 on 2024-08-26 16:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskManagement', '0005_task_category_alter_task_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 26, 16, 52, 16, 626948, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
