# Generated by Django 5.1 on 2024-09-05 23:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskManagement', '0020_alter_task_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 5, 23, 54, 28, 794574, tzinfo=datetime.timezone.utc)),
        ),
    ]
