# Generated by Django 5.1 on 2024-09-06 00:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskManagement', '0025_alter_task_creator_alter_task_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 6, 0, 28, 30, 983571, tzinfo=datetime.timezone.utc)),
        ),
    ]
