# Generated by Django 5.1 on 2024-09-06 16:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskManagement', '0027_task_status_alter_task_category_alter_task_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 6, 16, 35, 15, 7360, tzinfo=datetime.timezone.utc)),
        ),
    ]
